#!/usr/bin/env bash
# a Bash script that ping an IP address passed as an argument.

if [[ $# -eq 0 ]]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
elif [[ $1 ]]
then
	ping -c 5 "$1"
fi
