#!/usr/bin/env bash
# Script that configures an Ubuntu server.

cp /etc/hosts ~/host.new
sed -i 's/^127.0.0.1\s*localhost/127.0.0.2	localhost/' ~/host.new
sed 'a 8.8.8.8	facebook.com' ~/host.new
cp -f ~/host.new /etc/hosts
